#: import Settings1 settings.Settings1

<MainScreen>:
    orientation: "vertical"

    MDToolbar:
        title: "{}. {}".format(app.current_map, app.status)
        md_bg_color: self.theme_cls.primary_dark

    MDTabs:
        id: tabs

        Tab:
            title: "Основная"

            Label:
                text: "Основная"

        Tab:
            title: "Логи"

            Label:
                text: "Логи"

        Tab:
            title: "Настройки"

            Settings1:
